name: Upgrade tree-sitter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade_tree_sitter:
    uses: monarchic-langs/.github/.github/workflows/maintenance-pr.yml@main
    with:
      maintenance_command: nix run .#upgrade-tree-sitter
      add_paths: |
        server/parser.info
        server/tree-sitter-bash.wasm
      branch: maintenance/upgrade-tree-sitter
      title: Auto upgrade tree-sitter-bash parser
      commit_message: "chore: update tree-sitter bash parser"
    secrets:
      MONARCHIC_GITHUB_PAT: ${{ secrets.MONARCHIC_GITHUB_PAT }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
