name: Verify changes

on:
  push:
    branches: [monarchic]
  workflow_dispatch:

jobs:
  verify:

    runs-on: ${{ fromJSON(vars.CI_RUNNER_LABELS) }}

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}

      - run: pnpm install --frozen-lockfile

      - name: Verify changes
        run: nix shell nixpkgs#shellcheck nixpkgs#shfmt -c pnpm verify:bail

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v5
        if: success() && matrix.node-version == '22.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./codecov.yml
